### ISSUE TITLE
Binary file is not recognized

### ISSUE THREAD

**Issue by bestbryant** [ndrs92/DesignSPHysics#12]
Hi All, I am newbie in this model

I have installed latest version of FreeCAD version 0.16 and DesignSPHysics

But there is problem on loading macro, here is the error report

Copyright (C) 2016 - Andrés Vieira (anvieiravazquez@gmail.com)
EPHYSLAB Environmental Physics Laboratory, Universidade de Vigo

This file is part of DesignSPHysics.

DesignSPHysics is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

DesignSPHysics is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with DesignSPHysics.  If not, see <http://www.gnu.org/licenses/>.

[DesignSPHysics] Found data file. Loading data from disk.
**[DesignSPHysics] [WARNING]: One or more of the executables in the setup is not correct. Check plugin setup to fix missing binaries**
[DesignSPHysics] Loading data is done.

I have select the correct path but **FreeCAD couldnt recognize the file.**

I am using **HP workstation Z440.**

Thank you
 
![image](https://user-images.githubusercontent.com/31584642/30001349-4fe64b5c-90c6-11e7-84cf-23088a10e755.png)

**Comment by ndrs92** [comment]
Hi there!

I'm sorry I've not replied before. I was on vacation. I'll check the executable recognition to ensure that error does not happen.

What version of DualSPHysics executables are you trying to use? Can you post me a screenshot of just executing gencase (without parameters)? (Like this)

![image](https://user-images.githubusercontent.com/6155245/30017576-1a2cedd8-915a-11e7-89db-fc8d9e4faacb.png)

For now I only check that <GENCASE4> appears at the top of the copyright notice, so in your case, that is not recognised, is probable that your GenCase does not output the license like this, so hence the screenshot petition.

Thanks for reporting the error. I'll try to harden up the exe recognition!

**Comment by bestbryant** [comment]
Hi Andreas,

Thank you for your response!
Here is the screenshot of the executable file
Hope this solves the problem
![image](https://user-images.githubusercontent.com/31584642/30017942-fe740888-9195-11e7-8c7f-e737776dfcad.png)

**Comment by ndrs92** [comment]
Hi!

I've been looking at your problem and took me a lot of time until a colleague suggested a thing...

The problem that you're having is that your executable path is inside of a path with spaces on it (`coastal lab pc`)

This is going to be fixed in the next release. Meanwhile, please put the executables into a place without spaces (i.e: `C:\dualsphysics\`).

Sorry for the inconvenience and thank you for helping with your issue.
