### ISSUE TITLE
FreeCAD thread dedicated to DesignSPHysics

### ISSUE THREAD

**Issue by luzpaz** [ndrs92/DesignSPHysics#22]
https://forum.freecadweb.org/viewtopic.php?f=37&t=20595&start=10#p206740

**Comment by ndrs92** [comment]
Thank you for the info! I didn't even know that was there, and seems it was opened a long time ago. I've already posted in there and I'll try to check it from time to time.

**Comment by luzpaz** [comment]
@ndrs92 you can set the phpbb forum to notify you when the thread is active. Just a suggestion.

**Comment by ndrs92** [comment]
Thanks for the suggestion. I've already done it.... strangely I had to change the board theme, as in the FreeCAD one I haven't been able to find the button...

**Comment by luzpaz** [comment]
@kkremitzki https://github.com/ndrs92/DesignSPHysics/issues/22#issuecomment-361230870 seems the FC theme for phpbb doesn't show this link
